### PR TITLE
Translate Python to Vyxal

### PR DESCRIPTION
**Pull request by ysthakur**
A minimal but efficient approach to translate arbitrary Python expressions to Vyxal. This will be extremely useful in decompiling transpiled Vyxal code.

### CODE REVIEW

**Review by pxeger — APPROVED** [review]
I mean, sure, but why?

**Review by PyGamer0 — APPROVED** [review]
very 🍪

**Comment by hyper-neutrino** [comment]
no

**Comment by Lyxal** [comment]
I, on the other hand, love fun!

**Review by Lyxal — APPROVED** [review]

**Pull request merged**
